package com.example.demo.pojo;

public class BorrowManagement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrowmanagement.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrowmanagement.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrowmanagement.concern
     *
     * @mbggenerated
     */
    private String concern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrowmanagement.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrowmanagement.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrowmanagement.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrowmanagement.id
     *
     * @return the value of borrowmanagement.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrowmanagement.id
     *
     * @param id the value for borrowmanagement.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrowmanagement.name
     *
     * @return the value of borrowmanagement.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrowmanagement.name
     *
     * @param name the value for borrowmanagement.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrowmanagement.concern
     *
     * @return the value of borrowmanagement.concern
     *
     * @mbggenerated
     */
    public String getConcern() {
        return concern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrowmanagement.concern
     *
     * @param concern the value for borrowmanagement.concern
     *
     * @mbggenerated
     */
    public void setConcern(String concern) {
        this.concern = concern == null ? null : concern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrowmanagement.user
     *
     * @return the value of borrowmanagement.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrowmanagement.user
     *
     * @param user the value for borrowmanagement.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrowmanagement.num
     *
     * @return the value of borrowmanagement.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrowmanagement.num
     *
     * @param num the value for borrowmanagement.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrowmanagement.time
     *
     * @return the value of borrowmanagement.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrowmanagement.time
     *
     * @param time the value for borrowmanagement.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}