package com.example.demo.pojo;

public class LiabraryMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liabrarymessage.bookname
     *
     * @mbggenerated
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liabrarymessage.bookconcern
     *
     * @mbggenerated
     */
    private String bookconcern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liabrarymessage.writer
     *
     * @mbggenerated
     */
    private String writer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liabrarymessage.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liabrarymessage.bookname
     *
     * @return the value of liabrarymessage.bookname
     *
     * @mbggenerated
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liabrarymessage.bookname
     *
     * @param bookname the value for liabrarymessage.bookname
     *
     * @mbggenerated
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liabrarymessage.bookconcern
     *
     * @return the value of liabrarymessage.bookconcern
     *
     * @mbggenerated
     */
    public String getBookconcern() {
        return bookconcern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liabrarymessage.bookconcern
     *
     * @param bookconcern the value for liabrarymessage.bookconcern
     *
     * @mbggenerated
     */
    public void setBookconcern(String bookconcern) {
        this.bookconcern = bookconcern == null ? null : bookconcern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liabrarymessage.writer
     *
     * @return the value of liabrarymessage.writer
     *
     * @mbggenerated
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liabrarymessage.writer
     *
     * @param writer the value for liabrarymessage.writer
     *
     * @mbggenerated
     */
    public void setWriter(String writer) {
        this.writer = writer == null ? null : writer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liabrarymessage.number
     *
     * @return the value of liabrarymessage.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liabrarymessage.number
     *
     * @param number the value for liabrarymessage.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}