package com.example.demo.pojo;

public class ReturnManagement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnmanagement.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnmanagement.concern
     *
     * @mbggenerated
     */
    private String concern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnmanagement.returnperson
     *
     * @mbggenerated
     */
    private String returnperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returnmanagement.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnmanagement.name
     *
     * @return the value of returnmanagement.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnmanagement.name
     *
     * @param name the value for returnmanagement.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnmanagement.concern
     *
     * @return the value of returnmanagement.concern
     *
     * @mbggenerated
     */
    public String getConcern() {
        return concern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnmanagement.concern
     *
     * @param concern the value for returnmanagement.concern
     *
     * @mbggenerated
     */
    public void setConcern(String concern) {
        this.concern = concern == null ? null : concern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnmanagement.returnperson
     *
     * @return the value of returnmanagement.returnperson
     *
     * @mbggenerated
     */
    public String getReturnperson() {
        return returnperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnmanagement.returnperson
     *
     * @param returnperson the value for returnmanagement.returnperson
     *
     * @mbggenerated
     */
    public void setReturnperson(String returnperson) {
        this.returnperson = returnperson == null ? null : returnperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returnmanagement.number
     *
     * @return the value of returnmanagement.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returnmanagement.number
     *
     * @param number the value for returnmanagement.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}