package com.example.demo.dao;

import com.example.demo.pojo.ReturnManagement;

public interface ReturnManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnmanagement
     *
     * @mbggenerated
     */
    int insert(ReturnManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnmanagement
     *
     * @mbggenerated
     */
    int insertSelective(ReturnManagement record);
}